version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Asia/Tokyo'

    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      tanstack:
        patterns:
          - '@tanstack/react-query'
          - '@tanstack/react-query-devtools'
      mui:
        patterns:
          - '@mui/material'
          - '@mui/icons-material'
          - '@mui/system'
